version: "2"
services:
    alexa:
        build: alexa
        image: georgguttmann/alexa
        container_name: alexa
        restart: always
        expose:
            - "3000"
        ports:
            - "3000:3000"
        volumes:
            - ./alexa/alexa-fhem/:/root/alexa-fhem/
            - ./alexa/config/:/root/.alexa/
        networks:
            - fhem-network

networks:
    fhem-network:
        driver: bridge